/*class TattooArtist {
  constructor(uid, userUid, title, phone, email, instagramLink, facebookLink) {
    this.uid = uid; // Tattoo artist's unique identifier (generated by Firebase)
    this.userUid = userUid; // User's UID, who is also a tattoo artist
    this.title = title; // Artist's professional title or specialization
    this.phone = phone; // Artist's phone number
    this.email = email; // Artist's email
    this.instagramLink = instagramLink; // Link to Instagram profile
    this.facebookLink = facebookLink; // Link to Facebook profile
    this.createdAt = new Date(); // Timestamp when the artist profile is created
    this.updatedAt = new Date(); // Timestamp when the artist profile is last updated
  }

  // Method to update artist's information
  updateArtist({ title, phone, email, instagramLink, facebookLink }) {
    if (title) this.title = title;
    if (phone) this.phone = phone;
    if (email) this.email = email;
    if (instagramLink) this.instagramLink = instagramLink;
    if (facebookLink) this.facebookLink = facebookLink;
    this.updatedAt = new Date(); // Update the timestamp on any change
  }
}
*/

class TattooArtist {
  constructor(
    uid,
    userUid,
    title,
    phone,
    email,
    description,
    city,
    instagramLink,
    facebookLink,
    createdAt,
    updatedAt
  ) {
    this.uid = uid;
    this.userUid = userUid;
    this.title = title;
    this.phone = phone;
    this.email = email; // This will be pulled from the user's email
    this.description = description;
    this.city = city;
    this.instagramLink = instagramLink;
    this.facebookLink = facebookLink;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }
}
module.exports = TattooArtist;
