class TattooArtist {
  constructor(
    uid,
    userUid,
    title,
    phone,
    email,
    description,
    city,
    instagram_link,
    facebook_link,
    createdAt,
    updatedAt
  ) {
    this.uid = uid; // Tattoo artist's unique identifier (generated by Firebase)
    this.userUid = userUid; // User's UID, who is also a tattoo artist
    this.title = title; // Artist's professional title or specialization
    this.phone = phone; // Artist's phone number
    this.email = email; // Artist's email
    this.description = description; // Artist's description
    this.city = city; // Artist's city
    this.instagram_link = instagram_link; // Link to Instagram profile
    this.facebook_link = facebook_link; // Link to Facebook profile
    this.createdAt = createdAt; // Timestamp when the artist profile is created
    this.updatedAt = updatedAt; // Timestamp when the artist profile is last updated
  }

  // Method to update artist's information
  updateArtist({ title, phone, email, description, city, instagram_link, facebook_link }) {
    if (title) this.title = title;
    if (phone) this.phone = phone;
    if (email) this.email = email;
    if (description) this.description = description;
    if (city) this.city = city;
    if (instagram_link) this.instagram_link = instagram_link;
    if (facebook_link) this.facebook_link = facebook_link;
    this.updatedAt = new Date(); // Update the timestamp on any change
  }
}

module.exports = TattooArtist;
